server:
  port: 8083

spring:
  application:
    name: achievement-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/achievement_db
    username: achievement_user
    password: achievement_pass

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092