events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/quizzes {
            proxy_pass http://quiz-service:8082;
        }

        location /api/achievement/ {
            proxy_pass http://achievement-service:8083/api/achievement/;
        }

        location /api/notifications/ {
            proxy_pass http://notification-service:8084/api/notifications/;
        }
    }
}