events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/quiz/ {
            proxy_pass http://quiz-service:8080;
        }

        location /api/achievement/ {
            proxy_pass http://achievement-service:8083;
        }
    }
}